### ISSUE TITLE
Osiris code

### ISSUE THREAD

**Issue by TrumeAAA** [vkbo/OsirisAnalysis#1]
Excuse me, sir, I am very sorry to bother you, would you please tell me where can I download the osiris source code because I cannot find it on github, Thank you very much. Have a nice day!

**Comment by vkbo** [comment]
Hi there. I'm not a "sir" by the way. 

Osiris is not open source. It is maintained by the Laser and Plasma group at the Institute of Technology in Lisbon, Portugal.

See: http://epp.tecnico.ulisboa.pt/osiris/
