### ISSUE TITLE
Wigner transform

### ISSUE THREAD

**Issue by alexanatoly** [vkbo/OsirisAnalysis#2]
Hi, 

Would it be possible to let me know how to perform ```Wigner transform``` in OSIRIS code ?

For example, as done in Fig 1 (c,d,e) in the following article:
https://iopscience.iop.org/article/10.1088/1367-2630/14/2/023057/pdf

Thanks,
Alex

**Comment by vkbo** [comment]
Please direct questions about Osiris to their group: http://epp.tecnico.ulisboa.pt/osiris/
